- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-python3-wallaby-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - virtualbmc-tempest-ironic-ipmi-iscsi
    gate:
      jobs:
        - virtualbmc-tempest-ironic-ipmi-iscsi
