- project:
    templates:
        - release-notes-jobs
        - publish-openstack-sphinx-docs
    check:
      jobs:
        - virtualbmc-tempest-ironic-ipmi-iscsi
        - openstack-tox-lower-constraints
    gate:
      jobs:
        - virtualbmc-tempest-ironic-ipmi-iscsi
        - openstack-tox-lower-constraints
